// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

/**
 * Generated by kmapx: BoxSrc → BoxDto.
 */
public fun BoxSrc.toBoxDto(): BoxDto = BoxDto(
  items = items.map { it.toAddressDto() },
)
