// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

/**
 * Generated by kmapx: BoxSrc → BoxDto.
 */
public fun BoxSrc.toBoxDtoMap(): BoxDto = BoxDto(
  items = items.mapValues { (_, v) -> v.toAddressDto() },
)
