// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

import dev.kmapx.annotations.GeneratedMapping

/**
 * Generated by kmapx: BoxSrc → BoxDto.
 */
@GeneratedMapping(
  source = "dev.kmapx.codegen.BoxSrc",
  target = "dev.kmapx.codegen.BoxDto",
)
public fun BoxSrc.toBoxDto(): BoxDto = BoxDto(
  items = items.map { it.toAddressDto() },
)
