// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

/**
 * Generated by kmapx: CardSrc → CardDto.
 */
public fun CardSrc.toCardDto(): CardDto = when {
  nickname != null && bio != null -> CardDto(
    id = id,
    nickname = nickname,
    bio = bio,
  )
  nickname != null -> CardDto(
    id = id,
    nickname = nickname,
  )
  bio != null -> CardDto(
    id = id,
    bio = bio,
  )
  else -> CardDto(
    id = id,
  )
}
