// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

import dev.kmapx.annotations.GeneratedMapping

/**
 * Generated by kmapx: CardSrc → CardDto.
 */
@GeneratedMapping(
  source = "dev.kmapx.codegen.CardSrc",
  target = "dev.kmapx.codegen.CardDto",
)
public fun CardSrc.toCardDto(): CardDto = when {
  nickname != null && bio != null -> CardDto(
    id = id,
    nickname = nickname,
    bio = bio,
  )
  nickname != null -> CardDto(
    id = id,
    nickname = nickname,
  )
  bio != null -> CardDto(
    id = id,
    bio = bio,
  )
  else -> CardDto(
    id = id,
  )
}
