// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

public object CustomerPatcherImpl : CustomerPatcher {
  override fun apply(target: PatchCustomer, patch: PatchCustomerDto): PatchCustomer = target.copy(
    name = patch.name ?: target.name,
    nickname = patch.nickname ?: target.nickname,
  )
}
