// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

import dev.kmapx.annotations.GeneratedMapping

/**
 * Generated by kmapx: EventSrc → EventDto.
 */
@GeneratedMapping(
  source = "dev.kmapx.codegen.EventSrc",
  target = "dev.kmapx.codegen.EventDto",
)
public fun EventSrc.toEventDto(): EventDto = EventDto(
  createdAt = ShortDate.convert(createdAt),
)
