// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

/**
 * Generated by kmapx: EventSrc → EventDto.
 */
public fun EventSrc.toEventDto(): EventDto = EventDto(
  createdAt = ShortDate.convert(createdAt),
)
