// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

import dev.kmapx.annotations.GeneratedMapping

/**
 * Generated by kmapx: NickSrc → NickDto.
 */
@GeneratedMapping(
  source = "dev.kmapx.codegen.NickSrc",
  target = "dev.kmapx.codegen.NickDto",
)
public fun NickSrc.toNickDtoWithDefault(): NickDto = NickDto(
  nickname = nickname ?: "N/A",
)
