// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

/**
 * Generated by kmapx: NickSrc → NickDto.
 */
public fun NickSrc.toNickDtoWithDefault(): NickDto = NickDto(
  nickname = nickname ?: "N/A",
)
