// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

/**
 * Generated by kmapx: NickSrc → NickDto.
 */
public fun NickSrc.toNickDtoOrThrow(): NickDto = NickDto(
  nickname = nickname ?: throw IllegalArgumentException("nickname must not be null mapping NickSrc -> NickDto"),
)
