// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

import dev.kmapx.annotations.GeneratedMapping

/**
 * Generated by kmapx: NickSrc → NickDto.
 */
@GeneratedMapping(
  source = "dev.kmapx.codegen.NickSrc",
  target = "dev.kmapx.codegen.NickDto",
)
public fun NickSrc.toNickDtoOrThrow(): NickDto = NickDto(
  nickname = nickname ?: throw IllegalArgumentException("nickname must not be null mapping NickSrc -> NickDto"),
)
