// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

import dev.kmapx.annotations.GeneratedMapping

/**
 * Generated by kmapx: Order → OrderDtoReversed.
 */
@GeneratedMapping(
  source = "dev.kmapx.codegen.Order",
  target = "dev.kmapx.codegen.OrderDtoReversed",
)
public fun Order.toOrderDtoReversed(): OrderDtoReversed = OrderDtoReversed(
  total = total,
  id = id.value,
)
