// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

/**
 * Generated by kmapx: Order → OrderDtoReversed.
 */
public fun Order.toOrderDtoReversed(): OrderDtoReversed = OrderDtoReversed(
  total = total,
  id = id.value,
)
