// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

/**
 * Generated by kmapx: Order → OrderDto.
 */
public fun Order.toOrderDto(): OrderDto = OrderDto(
  id = id.value,
  total = total,
)
