// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

import dev.kmapx.annotations.GeneratedMapping

/**
 * Generated by kmapx: Order → OrderDto.
 */
@GeneratedMapping(
  source = "dev.kmapx.codegen.Order",
  target = "dev.kmapx.codegen.OrderDto",
)
public fun Order.toOrderDto(): OrderDto = OrderDto(
  id = id.value,
  total = total,
)

/**
 * Generated by kmapx: Order → OrderSummary.
 */
@GeneratedMapping(
  source = "dev.kmapx.codegen.Order",
  target = "dev.kmapx.codegen.OrderSummary",
)
public fun Order.toOrderSummary(): OrderSummary = OrderSummary(
  total = total,
)
