// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

import dev.kmapx.annotations.GeneratedMapping

/**
 * Generated by kmapx: Payment → PaymentDto.
 */
@GeneratedMapping(
  source = "dev.kmapx.codegen.Payment",
  target = "dev.kmapx.codegen.PaymentDto",
)
public fun Payment.toPaymentDto(): PaymentDto = when (this) {
  is Payment.Approved -> toApproved()
  is Payment.Pending -> PaymentDto.Pending
}

/**
 * Generated by kmapx: Approved → Approved.
 */
public fun Payment.Approved.toApproved(): PaymentDto.Approved = PaymentDto.Approved(
  amount = amount,
)
