// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

/**
 * Generated by kmapx: Payment → PaymentDto.
 */
public fun Payment.toPaymentDto(): PaymentDto = when (this) {
  is Payment.Approved -> toApproved()
  is Payment.Pending -> PaymentDto.Pending
}

/**
 * Generated by kmapx: Approved → Approved.
 */
public fun Payment.Approved.toApproved(): PaymentDto.Approved = PaymentDto.Approved(
  amount = amount,
)
