// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

import dev.kmapx.annotations.GeneratedMapping

@GeneratedMapping(
  source = "dev.kmapx.codegen.Priority",
  target = "dev.kmapx.codegen.PriorityDto",
)
public fun Priority.toPriorityDto(): PriorityDto = when (this) {
  Priority.LOW -> PriorityDto.LOW
  Priority.HIGH -> PriorityDto.HIGH
}
