// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

public fun Priority.toPriorityDto(): PriorityDto = when (this) {
  Priority.LOW -> PriorityDto.LOW
  Priority.HIGH -> PriorityDto.HIGH
}
