// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

import dev.kmapx.annotations.GeneratedMapping

/**
 * Generated by kmapx: ProfileSrc → ProfileDto.
 */
@GeneratedMapping(
  source = "dev.kmapx.codegen.ProfileSrc",
  target = "dev.kmapx.codegen.ProfileDto",
)
public fun ProfileSrc.toProfileDto(): ProfileDto = if (nickname != null) ProfileDto(
  name = name,
  nickname = nickname,
) else ProfileDto(
  name = name,
)
