// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

/**
 * Generated by kmapx: ProfileSrc → ProfileDto.
 */
public fun ProfileSrc.toProfileDto(): ProfileDto = if (nickname != null) ProfileDto(
  name = name,
  nickname = nickname,
) else ProfileDto(
  name = name,
)
