// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

import dev.kmapx.other.Temperature
import dev.kmapx.other.temperatureOf

/**
 * Generated by kmapx: Reading → Temperature.
 */
public fun Reading.toTemperature(): Temperature = temperatureOf(
  kelvin = kelvin,
)
