// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

/**
 * Generated by kmapx: Reading → Temperature.
 */
public fun Reading.toTemperature(): Temperature = Temperature.fromKelvin(
  kelvin = kelvin,
)
