// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

import dev.kmapx.annotations.GeneratedMapping
import dev.kmapx.other.Temperature
import dev.kmapx.other.temperatureOf

/**
 * Generated by kmapx: Reading → Temperature.
 */
@GeneratedMapping(
  source = "dev.kmapx.codegen.Reading",
  target = "dev.kmapx.other.Temperature",
)
public fun Reading.toTemperature(): Temperature = temperatureOf(
  kelvin = kelvin,
)
