// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

import dev.kmapx.annotations.GeneratedMapping

/**
 * Generated by kmapx: Reading → Temperature.
 */
@GeneratedMapping(
  source = "dev.kmapx.codegen.Reading",
  target = "dev.kmapx.codegen.Temperature",
)
public fun Reading.toTemperature(): Temperature = Temperature.fromKelvin(
  kelvin = kelvin,
)
