// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

import dev.kmapx.annotations.GeneratedMapping

/**
 * Generated by kmapx: TaskSrc → TaskTarget.
 */
@GeneratedMapping(
  source = "dev.kmapx.codegen.TaskSrc",
  target = "dev.kmapx.codegen.TaskTarget",
)
public fun TaskSrc.toTaskTarget(): TaskTarget = TaskTarget(
  id = id,
).also {
  it.status = status
}
