// Generated by kmapx. Do not edit.
package dev.kmapx.codegen

/**
 * Generated by kmapx: TaskSrc → TaskTarget.
 */
public fun TaskSrc.toTaskTarget(): TaskTarget = TaskTarget(
  id = id,
).also {
  it.status = status
}
